### ISSUE TITLE
How does this template engine fit into Ada?

### ISSUE THREAD

**Issue by Joebeazelman** [rocher/mold#3]
Very nice project and may be useful. It appears to be a standalone template processing tool, but aside from being written in Ada, what's Ada about it? The documentation says it can be included as a library, but the API seems limited to indirect processing using files.

**Comment by rocher** [comment]
> The documentation says it can be included as a library, but the API seems limited to indirect processing using files.

That refers to `mold_lib`: it's an Ada library, so it can be included in an Ada project using Alire.

There are plans not only to process files, but also to allow in-memory processing (variable replacement in strings). Also, text filters can be a completely separate library.
